AllCops:
  TargetRubyVersion: 2.3

# Project styling

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: true
Lint/EndAlignment:
  AlignWith: variable

# Concessions (remove these if possible / appropriate).

Style/FrozenStringLiteralComment:
  Enabled: false # forces addition of frozen string literal directive to all files. WTF.
Metrics/LineLength:
  Max: 320 # default was 80.
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20 # default was 10.
Metrics/ClassLength:
  Max: 500 # default was 100.
Metrics/AbcSize:
  Max: 30 # default is 15.
Style/GuardClause:
  Enabled: false # this thing is annoying, and can lead to not-as-readable code.
